name: CI/CD MLflow Local

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # kalau kamu punya requirements.txt, lebih enak pakai:
          # pip install -r requirements.txt
          pip install mlflow seaborn pandas matplotlib scikit-learn joblib dagshub

      - name: Run MLflow Project
        run: |
          # asumsinya file MLproject ada di root repo
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get_runid
        run: |
          # Ambil run_id terbaru dari experiment 0 (Default)
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | sed 's|mlruns/0/||;s|/||')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload model + artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/0/${{ env.RUN_ID }}/artifacts/

      - name: Build Docker image from MLflow model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/rf_best_model" \
            --name "${{ secrets.DOCKER_IMAGE_NAME }}" \
            --env-manager local

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          # pakai token / access token
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag "${{ secrets.DOCKER_IMAGE_NAME }}" \
            "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest"
